import type { TelehealthSession } from "./types";

export const SESSIONS: TelehealthSession[] = [
  {
    id: "TH-2024-001",
    patientId: "P-001",
    patient: "Sarah Johnson",
    initials: "SJ",
    age: 34,
    doctor: "Dr. Emily Chen",
    specialty: "Cardiology",
    reason: "Follow-up on hypertension management",
    date: new Date().toISOString().split("T")[0],
    time: "09:00",
    duration: 30,
    status: "live",
    sessionType: "video",
    consultType: "followup",
    platform: "Zoom",
    waitTime: "5",
  },
  {
    id: "TH-2024-002",
    patientId: "P-002",
    patient: "Michael Rodriguez",
    initials: "MR",
    age: 28,
    doctor: "Dr. James Wilson",
    specialty: "Dermatology",
    reason: "Skin rash evaluation",
    date: new Date().toISOString().split("T")[0],
    time: "10:30",
    duration: 20,
    status: "scheduled",
    sessionType: "video",
    consultType: "initial",
    platform: "Teams",
  },
  {
    id: "TH-2024-003",
    patientId: "P-003",
    patient: "Emma Davis",
    initials: "ED",
    age: 45,
    doctor: "Dr. Sarah Martinez",
    specialty: "Endocrinology",
    reason: "Diabetes management consultation",
    date: new Date().toISOString().split("T")[0],
    time: "14:00",
    duration: 45,
    status: "scheduled",
    sessionType: "audio",
    consultType: "followup",
    platform: "Phone",
  },
  {
    id: "TH-2024-004",
    patientId: "P-004",
    patient: "David Thompson",
    initials: "DT",
    age: 62,
    doctor: "Dr. Robert Lee",
    specialty: "Pulmonology",
    reason: "COPD follow-up",
    date: new Date(Date.now() - 86400000).toISOString().split("T")[0],
    time: "11:15",
    duration: 25,
    status: "completed",
    sessionType: "video",
    consultType: "followup",
    platform: "Zoom",
    rating: 5,
    notes: "Patient reports improved breathing with new inhaler regimen. Will continue current treatment plan.",
  },
  {
    id: "TH-2024-005",
    patientId: "P-005",
    patient: "Lisa Anderson",
    initials: "LA",
    age: 29,
    doctor: "Dr. Maria Garcia",
    specialty: "Gynecology",
    reason: "Annual check-up",
    date: new Date(Date.now() - 86400000).toISOString().split("T")[0],
    time: "15:45",
    duration: 30,
    status: "completed",
    sessionType: "video",
    consultType: "initial",
    platform: "Teams",
    rating: 4,
    notes: "Routine annual examination completed. All vitals normal. Next appointment in 1 year.",
  },
  {
    id: "TH-2024-006",
    patientId: "P-006",
    patient: "James Wilson",
    initials: "JW",
    age: 51,
    doctor: "Dr. Jennifer Brown",
    specialty: "Orthopedics",
    reason: "Knee pain assessment",
    date: new Date(Date.now() - 2 * 86400000).toISOString().split("T")[0],
    time: "13:30",
    duration: 40,
    status: "missed",
    sessionType: "video",
    consultType: "initial",
    platform: "Zoom",
  },
  {
    id: "TH-2024-007",
    patientId: "P-007",
    patient: "Anna Kim",
    initials: "AK",
    age: 38,
    doctor: "Dr. David Park",
    specialty: "Psychiatry",
    reason: "Anxiety management session",
    date: new Date(Date.now() - 3 * 86400000).toISOString().split("T")[0],
    time: "16:00",
    duration: 50,
    status: "completed",
    sessionType: "chat",
    consultType: "followup",
    platform: "Secure Chat",
    rating: 5,
    notes: "Patient showing good progress with CBT techniques. Homework completed successfully.",
  },
  {
    id: "TH-2024-008",
    patientId: "P-008",
    patient: "Robert Taylor",
    initials: "RT",
    age: 67,
    doctor: "Dr. Linda White",
    specialty: "Geriatrics",
    reason: "Medication review",
    date: new Date(Date.now() - 4 * 86400000).toISOString().split("T")[0],
    time: "10:00",
    duration: 35,
    status: "cancelled",
    sessionType: "audio",
    consultType: "followup",
    platform: "Phone",
  },
];